title: Tchelinux Live
email: rafasgj@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Modelo de site para eventos do Tchelinux.
baseurl: ""
url: ""
plugins:
  - jekyll-liquify
